### ISSUE TITLE
Astron Related DC AI crash - Connection/Internalrepository

### ISSUE THREAD

**Issue by voarsh** [Astron/Astron#333]
```python
Traceback (most recent call last):
File "C:\Panda3D-1.9.0\direct\distributed\ConnectionRepository.py", line 613,
in readerPollUntilEmpty
while self.readerPollOnce():
File "C:\Panda3D-1.9.0\direct\distributed\ConnectionRepository.py", line 620,
in readerPollOnce
self.handleDatagram(self.private__di)
File "C:\Panda3D-1.9.0\direct\distributed\AstronInternalRepository.py", line 2
28, in handleDatagram
self.handleObjEntry(di, msgType == STATESERVER_OBJECT_ENTER_AI_WITH_REQUIRED
_OTHER)
File "C:\Panda3D-1.9.0\direct\distributed\AstronInternalRepository.py", line 2
75, in handleObjEntry
do = dclass.getClassDef()(self)
TypeError: init() takes exactly 3 arguments (2 given)
:task(error): Exception occurred in PythonTask readerPollTask-36432992
Traceback (most recent call last):
File "C:\Panda3D-1.9.0\python\lib\runpy.py", line 162, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "C:\Panda3D-1.9.0\python\lib\runpy.py", line 72, in _run_code
exec code in run_globals
File "C:\Users\Administrator\tt\toontown\ai\Se
rviceStart.py", line 48, in <module>
run()
File "otp\ai\AIBase.py", line 190, in run
self.taskMgr.run()
File "C:\Panda3D-1.9.0\direct\task\Task.py", line 502, in run
self.step()
File "C:\Panda3D-1.9.0\direct\task\Task.py", line 460, in step
self.mgr.poll()
File "C:\Panda3D-1.9.0\direct\distributed\ConnectionRepository.py", line 613,
in readerPollUntilEmpty
while self.readerPollOnce():
File "C:\Panda3D-1.9.0\direct\distributed\ConnectionRepository.py", line 620,
in readerPollOnce
self.handleDatagram(self.private__di)
File "C:\Panda3D-1.9.0\direct\distributed\AstronInternalRepository.py", line 2
28, in handleDatagram
self.handleObjEntry(di, msgType == STATESERVER_OBJECT_ENTER_AI_WITH_REQUIRED
_OTHER)
File "C:\Panda3D-1.9.0\direct\distributed\AstronInternalRepository.py", line 2
75, in handleObjEntry
do = dclass.getClassDef()(self)
TypeError: init() takes exactly 3 arguments (2 given)
```

This error has happened a few times in the past, but has become more frequent and would like any pointers to know if it's a problem with my code, Astron or some problem with DC files. Strangely it doesn't happen when where is no user activity. I've had it running for a day without any activity and this error hasn't popped up. Any pointers would be useful, thanks.

**Comment by loblao** [comment]
Running two state servers with same channel too much? Github issues are not support.

**Comment by voarsh** [comment]
Hi, sorry for posting here.
I have tried to add more StateServers via /astron/config/astron.yaml but I am sure that's not how you add more.

I have never managed to get multiple AI's running on more than one machine. Can you explain how I might add more StateServers properly?

**Comment by AlJaMa** [comment]
@voarsh This looks like a problem with your Panda3D code. Not an issue with Astron.

**Comment by xHarv14** [comment]
Also: https://github.com/Astron/Astron/wiki/Not-Toontown

**Comment by bobbybee** [comment]
In the future (or if this issue is persisting), please ask in our IRC channel. Astron has no official support, as this is a volunteer project, but many of our developers and users idle there; if you have a very clear question, stick around and hopefully one of us will be able to answer it :)
